
export const enum REDIS_CONNECTION_STATUS {
  END = 'end',
  CONNECT = 'connect',
  ERROR = 'error'
}

export const ORDER_EVENTS = {
  CREATED: "ORDER_CREATED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  CONFIRMED: "ORDER_CONFIRMED",
  SHIPPED: "ORDER_SHIPPED",
  CANCELLED: "ORDER_CANCELLED",
  DELIVERED: "ORDER_DELIVERED"
};

export const INVENTORY_EVENTS = {
  RESERVED: "INVENTORY_RESERVED",
  STOCK_UPDATE: "INVENTORY_STOCK_UPDATE",
  FAILED: "INVENTORY_FAILED",
  RELEASED: "INVENTORY_RELEASED",
};